Merge test workflow
tigergraph/CoPilot pull request #115
Opened 2024-04-12 19:34 UTC by abubakkar2024

- conftest.py added to run tests under certain conditions when to skip and continue running them. All tests fail when unable to collect imports and milvus not enabled at specified port, hence conf code file assists in skipping them when the substring occur in the test code. ( milvus exception)
- Added a github actions workflow to run pytests on merge

2024-04-12 19:41 UTC, parkererickson-tg requested changes
can we gitignore the .idea directory?

Doesn't look like the action worked either

2024-04-12 19:42 UTC, abubakkar2024 commented
> can we gitignore the .idea directory?
> 
> Doesn't look like the action worked either

will make the changes

2024-05-09 13:55 UTC, parkererickson-tg approved these changes
Confused about ECC and tg_proxy changes - don't want to break these

2024-05-09 13:55 UTC, parkererickson-tg commented on app/metrics/tg_proxy.py
Is this rebased with main?

2024-05-09 13:55 UTC, parkererickson-tg commented on app/sync/eventual_consistency_checker.py
Is this rebased?

2024-05-09 14:06 UTC, ahmed-tg commented on app/sync/eventual_consistency_checker.py
thanks fixed!

2024-05-09 14:18 UTC, merged