[GML-1567] feat(copilot): Add TG graph algorithms to InquiryAI;
tigergraph/CoPilot pull request #151
Opened 2024-04-29 16:53 UTC by katinar

2024-04-30 14:28 UTC, RobRossmiller-TG commented on app/embeddings/milvus_embedding_store.py
> +        connections.connect(**self.milvus_connection)
note to team. double check if we need to connect again

2024-04-30 15:23 UTC, RobRossmiller-TG requested changes

2024-04-30 19:50 UTC, parkererickson-tg reviewed
Agree with @RobRossmiller-TG 's comments, otherwise LGTM

2024-04-30 20:42 UTC, katinar commented on app/embeddings/milvus_embedding_store.py
> +        connections.connect(**self.milvus_connection)
I just tested it and looks like we don't need to reconnect.

2024-05-01 19:34 UTC, parkererickson-tg approved these changes

2024-05-08 16:33 UTC, RobRossmiller-TG approved these changes

2024-05-08 19:09 UTC, parkererickson-tg approved these changes

2024-05-08 19:09 UTC, merged