TCE-4255 feat(cicd): Integrate the CoPilot repo CI/CD with TGCloud
tigergraph/CoPilot pull request #169
Opened 2024-05-29 02:57 UTC by pengchengrun

2024-06-04 21:54 UTC, parkererickson-tg requested changes

2024-06-04 21:54 UTC, parkererickson-tg commented on .github/workflows/pre-merge-test.yml
> +      - dev
Due to the branch naming, this should be `cloud-dev`

2024-06-06 23:33 UTC, billshitg commented on .github/workflows/pre-merge-test.yml
> +      - dev
And this PR should be merged into the cloud-dev branch as well instead of dev

2024-06-07 13:38 UTC, parkererickson-tg commented on .github/workflows/pre-merge-test.yml
> +      - dev
To keep actions consistent, we should merge it into dev and cloud-dev

2024-07-08 02:18 UTC, pengchengrun commented on .github/workflows/pre-merge-test.yml
> +      - dev
i change branch name to cloud-dev

2024-07-08 16:36 UTC, billshitg approved these changes

2024-07-08 17:05 UTC, parkererickson-tg approved these changes

2024-07-29 17:54 UTC, merged