GML-1615 feedback collection and update endpoint
tigergraph/CoPilot pull request #201
Opened 2024-06-13 20:06 UTC by luzhoutg

2024-06-13 20:16 UTC, RobRossmiller-TG requested changes
rm run script, please

2024-06-13 20:22 UTC, RobRossmiller-TG requested changes
Couple comments/questions

2024-06-13 20:22 UTC, RobRossmiller-TG commented on chat-history/db/db.go
> +		if result := db.Model(&existingMessage).Updates(map[string]any{
Don't use `map[string]any` if necessary.  We should be able to do something like [this](https://gorm.io/docs/update.html#Update-Selected-Fields:~:text=db.Model(%26user).Select(%22Name%22%2C%20%22Age%22).Updates(User%7BName%3A%20%22new_name%22%2C%20Age%3A%200%7D))

2024-06-13 20:22 UTC, RobRossmiller-TG commented on common/py_schemas/schemas.py
> +    comment: Optional[str] = None
Why does comment have a None default, but not feedback?

2024-06-13 22:03 UTC, luzhoutg commented on common/py_schemas/schemas.py
> +    comment: Optional[str] = None
sure. add default as None

> Why does comment have a None default, but not feedback?

2024-06-13 22:06 UTC, luzhoutg commented on chat-history/db/db.go
> +		if result := db.Model(&existingMessage).Updates(map[string]any{
if result := db.Model(&existingMessage).Select("Feedback", "Comment").Updates(
			structs.Message{
				Feedback: message.Feedback,
				Comment:  message.Comment,
			}); result.Error != nil {
			return nil, result.Error
		}
		
changed now

> Don't use `map[string]any` if necessary. We should be able to do something like [this](https://gorm.io/docs/update.html#Update-Selected-Fields:~:text=db.Model(%26user).Select(%22Name%22%2C%20%22Age%22).Updates(User%7BName%3A%20%22new_name%22%2C%20Age%3A%200%7D))

2024-06-14 14:14 UTC, RobRossmiller-TG approved these changes

2024-06-14 14:14 UTC, merged