Gml 1824 regression test with out cypher support only
tigergraph/CoPilot pull request #248
Opened 2024-07-15 18:02 UTC by luzhoutg

regression test with cypher support but not hallucination and usefulness check

2024-07-17 19:53 UTC, parkererickson-tg requested changes

2024-07-17 19:53 UTC, parkererickson-tg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
This shouldn't be here

2024-07-17 19:53 UTC, parkererickson-tg commented on copilot/app/agent/agent.py
> +        llm_provider = OpenAI(llm_config["completion_service"], graphname=graphname)
Remove the graphname info here too

2024-07-17 20:00 UTC, parkererickson-tg requested changes
We want to optionally enable cypher generation

2024-07-17 21:34 UTC, parkererickson-tg requested changes
We shouldn't completely remove cypher

2024-07-17 22:15 UTC, luzhoutg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
If I remember correctly, @RobRossmiller-TG added it to ensure better performance for demo. since gpt-4 works better on transaction fraud and inquiryAI.

2024-07-17 22:17 UTC, luzhoutg commented
> We shouldn't completely remove cypher

Sure. I have added cypher support back as optional now.

2024-07-17 22:44 UTC, parkererickson-tg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
Yeah I don't think that we should ship that though. For the demo it worked well.

2024-07-17 22:53 UTC, luzhoutg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
sounds good. got it removed now

2024-07-17 22:54 UTC, luzhoutg commented on copilot/app/agent/agent.py
> +        llm_provider = OpenAI(llm_config["completion_service"], graphname=graphname)
removed it now.

2024-07-17 23:17 UTC, billshitg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
It was removed in the dev branch unless I missed it. Is this based on the latest dev?

2024-07-18 02:45 UTC, luzhoutg commented on common/llm_services/openai_service.py
> +        if graphname == "Transaction_Fraud":
Yes. it's based on the latest dev branch.

2024-07-18 16:48 UTC, billshitg approved these changes

2024-07-18 16:48 UTC, billshitg commented on copilot/app/agent/agent.py
> +            # cypher_gen_tool=self.cypher_tool,
Just double check, is cypher support still available and optional?

2024-07-18 17:11 UTC, luzhoutg commented on copilot/app/agent/agent.py
> +            # cypher_gen_tool=self.cypher_tool,
good catch. just added it back. should be good to go.

2024-07-18 17:39 UTC, billshitg approved these changes

2024-07-18 17:44 UTC, parkererickson-tg approved these changes

2024-07-18 19:21 UTC, merged

2024-07-18 23:43 UTC, billshitg commented on copilot/app/agent/agent.py
> +                    logger.info(f"testing steps {key}: {value}")
Missed this line. Do we need to log all the questions and generated answer?

2024-07-19 00:12 UTC, luzhoutg commented on copilot/app/agent/agent.py
> +                    logger.info(f"testing steps {key}: {value}")
We can comment it out. It was trying to understand which step went wrong during testing.