Gml 1809 feedback analysis access control
tigergraph/CoPilot pull request #256
Opened 2024-07-31 20:36 UTC by luzhoutg

2024-07-31 21:02 UTC, parkererickson-tg approved these changes

2024-07-31 23:35 UTC, billshitg commented on chat-history/routes/routes.go
> +		requestURL = fmt.Sprintf("%s:14240/gsqlserver/gsql/file", host)
For on-prem DBs, the port is not always 14240. Could we read it from config? How are we handling it for copilot?

2024-08-01 00:04 UTC, luzhoutg commented on chat-history/routes/routes.go
> +		requestURL = fmt.Sprintf("%s:14240/gsqlserver/gsql/file", host)
Thanks for pointing this out. Just push the updated. For CoPilot, pyTG have handled it already.

2024-08-01 14:21 UTC, RobRossmiller-TG requested changes
- Tests could do with a negative test (i.e. user is only allowed to see their messages, not all)
- One quirk in LoadConfig

Otherwise, looks good!

2024-08-01 14:21 UTC, RobRossmiller-TG commented on chat-history/config/config.go
> +		if err := json.Unmarshal(b, &cfg); err != nil {
If you're reading multiple config files, won't cfg just be the last file that was parsed in the list?

2024-08-01 20:48 UTC, luzhoutg commented on chat-history/config/config.go
> +		if err := json.Unmarshal(b, &cfg); err != nil {
Good catch. I update the loadConfig to load multiple config file in to different config structs. i.e., ChatDbConfig, and TgDbConfig. It looks like this: `	router.HandleFunc("GET /get_feedback", routes.GetFeedback(cfg.TgDbConfig.Hostname, cfg.TgDbConfig.GsPort, cfg.ChatDbConfig.ConversationAccessRoles, cfg.TgDbConfig.TgCloud))
`

2024-08-01 22:34 UTC, luzhoutg commented on chat-history/config/config.go
> +		if err := json.Unmarshal(b, &cfg); err != nil {
also added test cases for non-admin users and non-existent users.

2024-08-02 12:51 UTC, RobRossmiller-TG approved these changes

2024-08-02 16:58 UTC, merged