Gml 1821 graphrag retriever
tigergraph/CoPilot pull request #263
Opened 2024-08-19 16:15 UTC by parkererickson-tg

2024-08-19 20:43 UTC, billshitg approved these changes

2024-08-20 00:21 UTC, RobRossmiller-TG requested changes
One update to the async code within the retriever. Otherwise lgtm

2024-08-20 00:21 UTC, RobRossmiller-TG commented on copilot/app/supportai/retrievers/GraphRAG.py
> +            res = executor.submit(self.gather_candidates, question, context).result()
If we're going to mix async and not, we can just use an [asyncio runner](https://docs.python.org/3/library/asyncio-runner.html#running-an-asyncio-program) instead of starting a new thread and running asyncio in that

2024-08-20 00:44 UTC, parkererickson-tg commented
I tried this but it didn’t play nicely with FastAPI.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: RobRossmiller-TG ***@***.***>
Sent: Monday, August 19, 2024 7:21:51 PM
To: tigergraph/CoPilot ***@***.***>
Cc: Parker Erickson ***@***.***>; Author ***@***.***>
Subject: Re: [tigergraph/CoPilot] Gml 1821 graphrag retriever (PR #263)


@RobRossmiller-TG requested changes on this pull request.

One update to the async code within the retriever. Otherwise lgtm

________________________________

In copilot/app/supportai/retrievers/GraphRAG.py<https://github.com/tigergraph/CoPilot/pull/263#discussion_r1722534723>:

> +        loop = asyncio.new_event_loop()
+        asyncio.set_event_loop(loop)
+        tasks = [self._generate_candidate(question, c) for c in context]
+        res = loop.run_until_complete(asyncio.gather(*tasks))
+        loop.close()
+        return res
+
+    def retrieve_answer(self,
+                        question: str,
+                        community_level: int,
+                        top_k_answer_candidates: int = 1):
+        retrieved = self.search(question, community_level)
+        context = [x["attributes"] for x in retrieved[0]["selected_comms"]]
+
+        with ThreadPoolExecutor() as executor:
+            res = executor.submit(self.gather_candidates, question, context).result()


If we're going to mix async and not, we can just use an asyncio runner<https://docs.python.org/3/library/asyncio-runner.html#running-an-asyncio-program> instead of starting a new thread and running asyncio in that

—
Reply to this email directly, view it on GitHub<https://github.com/tigergraph/CoPilot/pull/263#pullrequestreview-2246751268>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A36AN3Q7G2NFW5AMUK7Q2Z3ZSKDZ7AVCNFSM6AAAAABMYEWX7SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBWG42TCMRWHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-20 15:03 UTC, RobRossmiller-TG approved these changes

2024-08-20 15:23 UTC, merged