feat(graphrag): add descriptions to all upserts, cooccurence edges
tigergraph/CoPilot pull request #270
Opened 2024-08-29 20:07 UTC by parkererickson-tg

2024-08-29 20:36 UTC, RobRossmiller-TG requested changes
Quick async func def change

2024-08-29 20:36 UTC, RobRossmiller-TG commented on common/extractors/LLMEntityRelationshipExtractor.py
> +    async def document_er_extraction(self, document):
Making this async will break the extract function. It would make sense to have one sync, one async function so we have sync and async options

2024-08-29 20:36 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/workers.py
> +                            {"relation_type": "DOC_CHUNK_COOCCURRENCE"},  # attributes
(nothing to change here)
How does doc-chunk co-occurence edges affect the louvain step?

2024-08-29 20:39 UTC, parkererickson-tg commented on eventual-consistency-service/app/graphrag/workers.py
> +                            {"relation_type": "DOC_CHUNK_COOCCURRENCE"},  # attributes
They act the same way as other relation types right now. We might want to think about modifying louvain to downrank the cooccurrence edge

2024-08-29 20:44 UTC, parkererickson-tg commented on common/extractors/LLMEntityRelationshipExtractor.py
> +    async def document_er_extraction(self, document):
Resolved. Not super happy with me just duplicating but can refactor later.

2024-08-30 00:00 UTC, RobRossmiller-TG approved these changes

2024-08-30 00:52 UTC, luzhoutg approved these changes

2024-08-30 13:34 UTC, merged