feat(graphrag): add type information upsert
tigergraph/CoPilot pull request #271
Opened 2024-08-30 19:49 UTC by parkererickson-tg

2024-09-03 18:38 UTC, RobRossmiller-TG requested changes

2024-09-03 18:38 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/community_summarizer.py
> +            return "error generating summary: {}".format(e)
This would write the error message as the summary, but not report the error. It would be easier to handle if this returned a tuple/dict 
```
{
    "error": True/False,
    "summary": "...",
}
```

2024-09-03 18:38 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
> +                return {"error": True}
This returns error=true, but it doesn't look like the code is using this return type anywhere. Also, the raise_for_status below this could throw an error. What is this try/except doing?

2024-09-03 18:38 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
> +    res = resp.json()["results"][0]["relationships_inserted"]
This `.json` would fail if the status of resp is not 200.

2024-09-03 20:12 UTC, parkererickson-tg commented on eventual-consistency-service/app/graphrag/util.py
> +                return {"error": True}
Sometimes entities contained malformed special characters (% instead of percent), etc., and that would throw an error.

2024-09-03 20:14 UTC, parkererickson-tg commented on eventual-consistency-service/app/graphrag/util.py
> +                return {"error": True}
The return type is being used in `check_vertex_exists()` as well, that is where I copied it from. Do you want me to change it to something different @RobRossmiller-TG ?

2024-09-04 13:00 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
> +                return {"error": True}
No, it's just that it doesn't look like any upstream function is checking the result. As far as throwing an error, it makes sense to me to either throw an error and have the system stop/have an upstream function catch the error or catch the error here and return the status as a dict

2024-09-04 13:04 UTC, RobRossmiller-TG requested changes

2024-09-04 13:04 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/community_summarizer.py
> +            return {"summary": f"Error: {e}"}
Sorry, not return the error as a summary. Return something like

                return {"error": True, "summary": "..." }

I don't think we want to write an error message as a vertex's summary

2024-09-04 13:04 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
> +        res = {"error": True}
Does the other res on 247 have an error key? The point of that is to be able to know for certain that this function returns something with the ability to check if it was successful (error: False). If error is False, then we can use the response we're expecting

2024-09-05 14:27 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/community_summarizer.py
>          return summary.summary
This is just missing the error field, so that we can check if the summarizer failed or not.

upstream code would be:
```
res = s.summarize(...)
if not res["error"]:
    # do something with the summary
else:
    # handle the error -- maybe retry?
```

2024-09-05 14:28 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
I think this could potentially return res.json() or None. Seems ok if we check for a None in the upstream code. Else, it would crash

2024-09-05 14:29 UTC, RobRossmiller-TG commented on eventual-consistency-service/app/graphrag/util.py
> +        logger.error(f"Check Vert EntityType err:\n{resp.text}")
Same here, this could return none if the status is not 200, but a result if the status is 200. Ok if we check for None in the caller.

2024-09-05 15:21 UTC, RobRossmiller-TG approved these changes

2024-09-05 15:44 UTC, luzhoutg approved these changes

2024-09-05 16:36 UTC, merged